---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: daggerok/quarkus-kubernetes-example-frontend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
              name: "http"
          readinessProbe:
            httpGet:
              scheme: HTTP
              port: 8080
              path: /health/ready
          livenessProbe:
            httpGet:
              scheme: HTTP
              port: 8080
              path: /health/live
          env:
            - name: BACKEND_HOST
              value: "backend"
      restartPolicy: Always
  selector:
    matchLabels:
      app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  sessionAffinity: None
  ports:
    - port: 8080
      protocol: TCP
      name: "http"
      targetPort: 8080
      nodePort: 30080
  type: NodePort
---
